location = /shanhe {
    return 301 /shanhe/;
}

location = /shanhe/index.html {
    alias /var/www/shanhe-lite/index.html;
    add_header Cache-Control "no-cache";
}

location = /shanhe/content.json {
    alias /var/www/shanhe-lite/content.json;
    add_header Cache-Control "no-cache";
}

location = /shanhe/service-worker.js {
    alias /var/www/shanhe-lite/service-worker.js;
    add_header Cache-Control "no-cache";
}

location = /shanhe/index.service.worker.js {
    alias /var/www/shanhe-lite/index.service.worker.js;
    add_header Cache-Control "no-cache";
}

location /shanhe/assets/ {
    alias /var/www/shanhe-lite/assets/;
    expires 30d;
    add_header Cache-Control "public, immutable";
}

location /shanhe/ {
    alias /var/www/shanhe-lite/;
    index index.html;
    expires 5m;
}

location = /shanhe-godot {
    return 301 /shanhe-godot/;
}

location /shanhe-godot/ {
    alias /var/www/shanhe-gongsheng/;
    index index.html;
    gzip_static on;
}
